#!/usr/bin/env python3
# generated by TauKit

#!/usr/bin/env python3
# Generated by TauKit
import ctypes, ctypes.wintypes as wt, random, threading, time, math

user32 = ctypes.windll.user32
gdi32  = ctypes.windll.gdi32
SW = user32.GetSystemMetrics(0)
SH = user32.GetSystemMetrics(1)
SRCCOPY   = 0x00CC0020
SRCINVERT = 0x00660046
SRCPAINT  = 0x00EE0086
NOTSRCCOPY= 0x00330008

running = True

class POINT(ctypes.Structure):
    _fields_ = [("x", ctypes.c_long), ("y", ctypes.c_long)]

class BITMAPINFOHEADER(ctypes.Structure):
    _fields_ = [
        ("biSize",wt.DWORD),("biWidth",wt.LONG),("biHeight",wt.LONG),
        ("biPlanes",wt.WORD),("biBitCount",wt.WORD),("biCompression",wt.DWORD),
        ("biSizeImage",wt.DWORD),("biXPelsPerMeter",wt.LONG),
        ("biYPelsPerMeter",wt.LONG),("biClrUsed",wt.DWORD),("biClrImportant",wt.DWORD),
    ]

class RGBTRIPLE(ctypes.Structure):
    _fields_ = [("rgbtBlue",ctypes.c_ubyte),("rgbtGreen",ctypes.c_ubyte),("rgbtRed",ctypes.c_ubyte)]

import math
import colorsys

phase=1

def _phase_switcher():
    global phase
    time.sleep(30); phase=2
    time.sleep(30); phase=3
    time.sleep(30)

# patinvert phases:[2]
def effect_patinvert():
    import colorsys,win32gui,win32con,win32api
    hue=0.0
    while running:
        if phase not in {2}:
            time.sleep(0.05); continue
        desktop=win32gui.GetDesktopWindow()
        hdc=win32gui.GetWindowDC(desktop)
        rgb=colorsys.hsv_to_rgb(hue%1.0,1.0,1.0)
        brush=win32gui.CreateSolidBrush(win32api.RGB(int(rgb[0]*255),int(rgb[1]*255),int(rgb[2]*255)))
        win32gui.SelectObject(hdc,brush)
        for _ in range(64):
            win32gui.BitBlt(hdc,4,4,SW,SH,hdc,0,0,win32con.SRCCOPY)
            win32gui.BitBlt(hdc,4,4,SW,SH,hdc,0,0,win32con.PATINVERT)
        win32gui.DeleteObject(brush); hue+=0.03
        win32gui.ReleaseDC(desktop,hdc)

# invert_circles phases:[2]
def effect_invert_circles():
    import win32gui,win32con
    _PATINVERT=0x005A0049
    def _inv_circ(hdc,x,y,r):
        if r<2: return
        rgn=gdi32.CreateEllipticRgn(x-r,y-r,x+r,y+r)
        gdi32.SelectClipRgn(hdc,rgn)
        gdi32.PatBlt(hdc,x-r,y-r,r*2,r*2,_PATINVERT)
        gdi32.SelectClipRgn(hdc,0)
        gdi32.DeleteObject(rgn)
    def _new_curve():
        return {"sx":random.uniform(80,500),"sy":random.uniform(80,500),
                "speed":random.uniform(0.3,2.2),"offset":random.uniform(0,6.28),
                "radius":random.randint(60,240)}
    brush=gdi32.CreateSolidBrush(0x00FFFFFF)
    desktop=user32.GetDesktopWindow()
    curves=[_new_curve() for _ in range(3)]
    cx2=float(SW//2); cy2=float(SH//2)
    lo_x=max(301,min(SW-301,300)); lo_y=max(301,min(SH-301,300))
    tx=random.randint(300,lo_x); ty=random.randint(300,lo_y)
    nxt=time.time()+2.0; last_loop=-1; prev_c=[]
    while running:
        if phase not in {2}:
            time.sleep(0.05); continue
        hdc=win32gui.GetWindowDC(desktop)
        gdi32.SelectObject(hdc,brush)
        for ox,oy,or_ in prev_c:
            _inv_circ(hdc,ox,oy,or_)
        prev_c=[]
        t2=time.time()
        if t2>=nxt:
            tx=random.randint(300,lo_x); ty=random.randint(300,lo_y); nxt=t2+2.0
        cx2+=(tx-cx2)*0.008; cy2+=(ty-cy2)*0.008
        lp=int(t2*0.25)
        if lp!=last_loop: last_loop=lp; curves=[_new_curve() for _ in range(3)]
        for c in curves:
            pulse=1.0+math.sin(t2*2.0+c["offset"])*0.3
            r=int(c["radius"]*pulse)
            x=int(cx2+math.sin(t2*c["speed"]+c["offset"])*c["sx"])
            y=int(cy2+math.cos(t2*c["speed"]*1.3+c["offset"])*c["sy"])
            _inv_circ(hdc,x,y,r); prev_c.append((x,y,r))
        win32gui.ReleaseDC(desktop,hdc)
        time.sleep(0.005)

# rgb_melt phases:[3]
def effect_rgb_melt():
    while running:
        if phase not in {3}:
            time.sleep(0.05); continue
        hdc=user32.GetDC(None)
        for _ in range(8):
            rx=random.randint(0,SW-1); width=random.randint(50,300)
            offset=random.randint(20,80)
            gdi32.BitBlt(hdc,rx,offset,width,SH,hdc,rx,0,SRCCOPY)
        user32.ReleaseDC(None,hdc)

# rgbtriple_np phases:[3]
def effect_rgbtriple_np():
    import numpy as np
    class BMI2(ctypes.Structure):
        _fields_=[("bmiHeader",BITMAPINFOHEADER)]
    bmi=BMI2(); bmi.bmiHeader.biSize=ctypes.sizeof(BITMAPINFOHEADER)
    bmi.bmiHeader.biWidth=SW; bmi.bmiHeader.biHeight=-SH
    bmi.bmiHeader.biPlanes=1; bmi.bmiHeader.biBitCount=24
    bmi.bmiHeader.biCompression=0
    stride=((SW*3+3)&~3)
    idx=np.arange(SW*SH,dtype=np.uint32)
    rows=(idx//SW).astype(np.uint32); cols=(idx%SW).astype(np.uint32)
    byte_b=(rows*stride+cols*3).astype(np.int64)
    byte_g=byte_b+1; byte_r=byte_b+2
    r_add=((idx&0xFF)&(idx&0xFF)).astype(np.uint8)
    g_add=(((idx>>8)&0xFF)&(idx&0xFF)).astype(np.uint8)
    b_add=(((idx>>16)&0xFF)&(idx&0xFF)).astype(np.uint8)
    while running:
        if phase not in {3}:
            time.sleep(0.05); continue
        desk=user32.GetDC(0); deskMem=gdi32.CreateCompatibleDC(desk)
        ppv=ctypes.c_void_p()
        scr=gdi32.CreateDIBSection(desk,ctypes.byref(bmi),0,ctypes.byref(ppv),0,0)
        gdi32.SelectObject(deskMem,scr); gdi32.BitBlt(deskMem,0,0,SW,SH,desk,0,0,SRCCOPY)
        if ppv.value:
            flat=np.ctypeslib.as_array((ctypes.c_uint8*(stride*SH)).from_address(ppv.value))
            flat[byte_r]=(flat[byte_r].astype(np.uint16)+r_add).astype(np.uint8)
            flat[byte_g]=(flat[byte_g].astype(np.uint16)+g_add).astype(np.uint8)
            flat[byte_b]=(flat[byte_b].astype(np.uint16)+b_add).astype(np.uint8)
        gdi32.BitBlt(desk,0,0,SW,SH,deskMem,0,0,SRCCOPY)
        user32.ReleaseDC(0,desk); gdi32.DeleteDC(deskMem); gdi32.DeleteObject(scr)

# new_swirl phases:[2]
def effect_new_swirl():
    import math
    cx, cy = SW//2, SH//2
    angle = 0
    while running:
        if phase not in {2}:
            time.sleep(0.05); continue
        hdc = user32.GetDC(0)
        hdcMem = gdi32.CreateCompatibleDC(hdc)
        hbm = gdi32.CreateCompatibleBitmap(hdc, SW, SH)
        gdi32.SelectObject(hdcMem, hbm)
        gdi32.BitBlt(hdcMem, 0, 0, SW, SH, hdc, 0, 0, SRCCOPY)
        for y in range(0, SH, 4):
            for x in range(0, SW, 4):
                dx = x - cx
                dy = y - cy
                dist = math.sqrt(dx*dx + dy*dy)
                if dist > 0:
                    a = math.atan2(dy, dx) + angle * (1 - dist / max(cx, cy))
                    sx = int(cx + math.cos(a) * dist)
                    sy = int(cy + math.sin(a) * dist)
                    if 0 <= sx < SW and 0 <= sy < SH:
                        gdi32.BitBlt(hdc, x, y, 4, 4, hdcMem, sx, sy, SRCCOPY)
        angle += 0.03
        gdi32.DeleteObject(hbm)
        gdi32.DeleteDC(hdcMem)
        user32.ReleaseDC(0, hdc)
        time.sleep(0.033)

# new_solarize phases:[3]
def effect_new_solarize():
    import numpy as np
    bmi = BITMAPINFOHEADER()
    bmi.biSize = ctypes.sizeof(BITMAPINFOHEADER)
    bmi.biWidth = SW
    bmi.biHeight = SH
    bmi.biPlanes = 1
    bmi.biBitCount = 24
    stride = (SW * 3 + 3) & ~3
    while running:
        if phase not in {3}:
            time.sleep(0.05); continue
        desk = user32.GetDC(0)
        deskMem = gdi32.CreateCompatibleDC(desk)
        ppv = ctypes.c_void_p()
        scr = gdi32.CreateDIBSection(desk, ctypes.byref(bmi), 0, ctypes.byref(ppv), 0, 0)
        gdi32.SelectObject(deskMem, scr)
        gdi32.BitBlt(deskMem, 0, 0, SW, SH, desk, 0, 0, SRCCOPY)
        if ppv.value:
            flat = np.ctypeslib.as_array((ctypes.c_uint8 * (stride * SH)).from_address(ppv.value))
            px = flat.reshape(SH, stride)[:,:SW*3].reshape(SH, SW, 3)
            # Solarize: if value > 127, invert it
            mask = px > 127
            px[mask] = 255 - px[mask]
        gdi32.BitBlt(desk, 0, 0, SW, SH, deskMem, 0, 0, SRCCOPY)
        user32.ReleaseDC(0, desk)
        gdi32.DeleteDC(deskMem)
        gdi32.DeleteObject(scr)
        time.sleep(0.033)

# new_posterize phases:[3]
def effect_new_posterize():
    import numpy as np
    bmi = BITMAPINFOHEADER()
    bmi.biSize = ctypes.sizeof(BITMAPINFOHEADER)
    bmi.biWidth = SW
    bmi.biHeight = SH
    bmi.biPlanes = 1
    bmi.biBitCount = 24
    stride = (SW * 3 + 3) & ~3
    while running:
        if phase not in {3}:
            time.sleep(0.05); continue
        desk = user32.GetDC(0)
        deskMem = gdi32.CreateCompatibleDC(desk)
        ppv = ctypes.c_void_p()
        scr = gdi32.CreateDIBSection(desk, ctypes.byref(bmi), 0, ctypes.byref(ppv), 0, 0)
        gdi32.SelectObject(deskMem, scr)
        gdi32.BitBlt(deskMem, 0, 0, SW, SH, desk, 0, 0, SRCCOPY)
        if ppv.value:
            flat = np.ctypeslib.as_array((ctypes.c_uint8 * (stride * SH)).from_address(ppv.value))
            px = flat.reshape(SH, stride)[:,:SW*3].reshape(SH, SW, 3)
            # Reduce to 4 bits per channel (0, 17, 34, ... 255)
            px = (px // 17) * 17
        gdi32.BitBlt(desk, 0, 0, SW, SH, deskMem, 0, 0, SRCCOPY)
        user32.ReleaseDC(0, desk)
        gdi32.DeleteDC(deskMem)
        gdi32.DeleteObject(scr)
        time.sleep(0.033)

# new_thermal phases:[3]
def effect_new_thermal():
    import numpy as np
    bmi = BITMAPINFOHEADER()
    bmi.biSize = ctypes.sizeof(BITMAPINFOHEADER)
    bmi.biWidth = SW
    bmi.biHeight = SH
    bmi.biPlanes = 1
    bmi.biBitCount = 24
    stride = (SW * 3 + 3) & ~3
    while running:
        if phase not in {3}:
            time.sleep(0.05); continue
        desk = user32.GetDC(0)
        deskMem = gdi32.CreateCompatibleDC(desk)
        ppv = ctypes.c_void_p()
        scr = gdi32.CreateDIBSection(desk, ctypes.byref(bmi), 0, ctypes.byref(ppv), 0, 0)
        gdi32.SelectObject(deskMem, scr)
        gdi32.BitBlt(deskMem, 0, 0, SW, SH, desk, 0, 0, SRCCOPY)
        if ppv.value:
            flat = np.ctypeslib.as_array((ctypes.c_uint8 * (stride * SH)).from_address(ppv.value))
            px = flat.reshape(SH, stride)[:,:SW*3].reshape(SH, SW, 3)
            brightness = (px[:,:,0].astype(np.uint16) + px[:,:,1] + px[:,:,2]) // 3
            # Thermal map: cold=blue, warm=red
            px[:,:,0] = np.clip(brightness * 2, 0, 255).astype(np.uint8)      # B
            px[:,:,1] = np.clip(255 - abs(brightness - 127) * 2, 0, 255).astype(np.uint8)  # G
            px[:,:,2] = np.clip(brightness * 2 - 255, 0, 255).astype(np.uint8) # R
        gdi32.BitBlt(desk, 0, 0, SW, SH, deskMem, 0, 0, SRCCOPY)
        user32.ReleaseDC(0, desk)
        gdi32.DeleteDC(deskMem)
        gdi32.DeleteObject(scr)
        time.sleep(0.033)

# donut phases:[1]
def effect_donut():
    import win32gui,math as _m
    msimg32=ctypes.windll.msimg32
    class BLENDFUNCTION(ctypes.Structure):
        _fields_=[("BlendOp",ctypes.c_byte),("BlendFlags",ctypes.c_byte),
                  ("SourceConstantAlpha",ctypes.c_byte),("AlphaFormat",ctypes.c_byte)]
    DI_NORMAL=0x0003; shell32="C:\\Windows\\System32\\shell32.dll"
    icons=[]
    for idx in range(0,200,10):
        try:
            large,small=win32gui.ExtractIconEx(shell32,idx,1)
            if large: icons.append(large[0])
            if small: win32gui.DestroyIcon(small[0])
        except: pass
    if not icons: return
    NM=18; Nm=10; RM=200; Rm=70; IS=24
    cx=SW//2; cy=SH//2; vx=random.choice([-5,5]); vy=random.choice([-4,4])
    aa=0.0; ab=0.0
    while running:
        if phase not in {1}:
            time.sleep(0.05); continue
        hdc=user32.GetDC(None)
        hdcm=gdi32.CreateCompatibleDC(hdc); hbm=gdi32.CreateCompatibleBitmap(hdc,SW,SH)
        gdi32.SelectObject(hdcm,hbm); gdi32.BitBlt(hdcm,0,0,SW,SH,hdc,0,0,SRCCOPY)
        bf=BLENDFUNCTION(0,0,45,0)
        msimg32.AlphaBlend(hdc,2,2,SW,SH,hdcm,0,0,SW,SH,bf)
        gdi32.DeleteObject(hbm); gdi32.DeleteDC(hdcm)
        ca=_m.cos(aa); sa=_m.sin(aa); cb=_m.cos(ab); sb=_m.sin(ab)
        ioff=random.randint(0,len(icons)-1)
        for i in range(NM):
            t=2*_m.pi*i/NM; ct=_m.cos(t); st=_m.sin(t)
            for j in range(Nm):
                p=2*_m.pi*j/Nm; cp=_m.cos(p); sp=_m.sin(p)
                ox=(RM+Rm*cp)*ct; oy=(RM+Rm*cp)*st; oz=Rm*sp
                rx=ox*ca-oy*sa; ry=ox*sa+oy*ca
                rz=oz*cb-ry*sb; ry2=oz*sb+ry*cb
                sc=600/(600+rz)
                sx2=int(cx+rx*sc); sy2=int(cy+ry2*sc)
                icon=icons[(i*Nm+j+ioff)%len(icons)]
                sz=max(8,int(IS*sc))
                win32gui.DrawIconEx(hdc,sx2-sz//2,sy2-sz//2,icon,sz,sz,0,0,DI_NORMAL)
        user32.ReleaseDC(None,hdc)
        cx+=vx; cy+=vy
        if cx<RM or cx>SW-RM: vx=-vx
        if cy<RM or cy>SH-RM: vy=-vy
        aa=(aa+0.04)%(2*_m.pi); ab=(ab+0.025)%(2*_m.pi)
        time.sleep(0.033)

THREAD_FUNCS=[effect_patinvert,effect_invert_circles,effect_rgb_melt,effect_rgbtriple_np,effect_new_swirl,effect_new_solarize,effect_new_posterize,effect_new_thermal,effect_donut,_phase_switcher]

threads=[threading.Thread(target=fn,daemon=True) for fn in THREAD_FUNCS]
for t in threads: t.start()
try:
    while True: time.sleep(1)
except KeyboardInterrupt:
    running=False
